-- liquibase formatted sql

-- changeset script:1
-- comment: Creation table categories
create table categories (
    id integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- changeset script:2
-- comment: Creation table products
create table products (
    id integer generated by default as identity,
    name varchar(255),
    category_id integer,
    primary key (id)
);

-- changeset script:3
-- comment: Creation table users
create table usuario (
    id integer generated by default as identity,
    password varchar(255) not null,
    username varchar(255) not null,
    primary key (id)
);

-- changeset script:4
-- comment: Creation categories
INSERT INTO categories(name) VALUES
    ( 'clothes'),
    ( 'toys'),
	( 'tools');

-- changeset script:5
-- comment: Creation products
INSERT INTO products(name, category_id) VALUES
    ( 't-shirt', 1 ),
    ( 'pants', 1 ),
    ( 'shoes', 1 ),
	( 'Max Steel', 2 ),
	( 'Barbie', 2 ),
	( 'Superman', 2 ),
	( 'Hammer', 3 ),
	( 'Helmet', 3 ),
	( 'Saw', 3 );

-- changeset script:6
-- comment: Creation users
INSERT INTO usuario(password, username) VALUES
	( '$2a$10$7JkbHDP3K0k1SkLiYt.Pq.MENlQFurkAEFwStoZ3nYPre3wxgIio2', 'user' );

